version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medrotina
      MYSQL_USER: medrotina_user
      MYSQL_PASSWORD: medrotina_pass
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
